Update localhist load process

diff --git a/bin/localhist b/bin/localhist
--- a/bin/localhist
+++ b/bin/localhist
@@ -1,29 +1,29 @@
 # vim: filetype=sh
 # localhist
 #
-#   localhist [h]elp    # Get help.
-#   localhist [o]n      # Set HISTFILE to <current dir>/bash_history
-#   localhist [j]oin    # Join by searching up in tree for 'bash_history'
-#   localhist [w]rite   # Write buffer to current HISTFILE
-#   localhist e[x]port  # Write buffer to specific file, with edit option
-#   localhist [r]ead    # Read from current HISTFILE to buffer
-#   localhist [i]mport  # Read from file(s) into buffer
-#   localhist of[f]     # Switch HISTFILE back to ~/bash_history
-#   localhist [s]how    # Show status
-#   localhist [d]ump    # Dump current histfile
-#   localhist [e]dit    # Load current history buffer into $EDITOR
-#   localhist [c]lear   # Clear buffer only
-#   localhist c[l]ean   # Clean current HISTFILE, removing unworthy stuff
-#   localhist [mem]clean# Clean current memory buffer removing unworthy stuff
-#   localhist co[m]pare # Compare current HISTFILE with ~/.bash_history
-#   localhist [z]merge  # Merge one or more file args into HISTFILE
-#   localhist [g]rep    # Search all ~/.localhist/* registered files
-#   localhist ca[t]alog # Print stats on all ~/.localhist registered files
+#   localhist -v|--version
+#   localhist [o]n       # Set HISTFILE to <current dir>/bash_history
+#   localhist [j]oin     # Join by searching up in tree for 'bash_history'
+#   localhist [w]rite    # Write buffer to current HISTFILE
+#   localhist e[x]port   # Write buffer to specific file, with edit option
+#   localhist [r]ead     # Read from current HISTFILE to buffer
+#   localhist [i]mport   # Read from file(s) into buffer
+#   localhist of[f]      # Switch HISTFILE back to ~/bash_history
+#   localhist [s]how     # Show status
+#   localhist [d]ump     # Dump current histfile
+#   localhist [e]dit     # Load current history buffer into $EDITOR
+#   localhist [c]lear    # Clear buffer only
+#   localhist c[l]ean    # Clean current HISTFILE, removing unworthy stuff
+#   localhist [mem]clean # Clean current memory buffer removing unworthy stuff
+#   localhist co[m]pare  # Compare current HISTFILE with ~/.bash_history
+#   localhist [z]merge   # Merge one or more file args into HISTFILE
+#   localhist [g]rep     # Search all ~/.localhist/* registered files
+#   localhist ca[t]alog  # Print stats on all ~/.localhist registered files
 #   lo             : : : :  E x a m p l e s   : : : :
-#   localhist on read   # Turn on, then read.
-#   localhist o r       # ... same thing, fewer letters
-#   localhist r l w     # Read, cLean, Write
-#   localhost w l m     # Write, cLean, coMpare with ~/.bash_history
+#   localhist on read    # Turn on, then read.
+#   localhist o r        # ... same thing, fewer letters
+#   localhist r l w      # Read, cLean, Write
+#   localhost w l m      # Write, cLean, coMpare with ~/.bash_history
 
 
 # stub() {
@@ -99,11 +99,11 @@ localhist_register() {
 localhist_export_help() {
     # Set up context and invoke localhist_export.sh
     (
-        [[ -x localhist-merge.sh ]] || { echo "ERROR: can't find localhist-merge.sh" >&2; exit 1; }
+        [[ -x ${LocalhistHome}/localhist-merge.sh ]] || { echo "ERROR: can't find ${LocalhistHome}/localhist-merge.sh" >&2; exit 1; }
         HISTFILE=$(mktemp)
         trap 'rm $HISTFILE' exit
         history -w
-        localhist-merge.sh $HISTFILE "$@"
+        ${LocalhistHome}/localhist-merge.sh $HISTFILE "$@"
     )
 }
 
@@ -113,8 +113,7 @@ localhist_memclean() {
     trap "rm $tmpfile &>/dev/null; HISTFILE=${orig_histfile};" return
     HISTFILE=${tmpfile}
     history -w
-    #histfile-cleanup.sh $HISTFILE &>/dev/null
-    histfile-cleanup.sh $HISTFILE
+    ${LocalhistHome}/localhist-cleanup.sh $HISTFILE
     history -c
     history -r
     echo "Ok: I cleaned history in buffer"
@@ -141,13 +140,16 @@ localhist_help() {
     [[ -r $LocalhistHelpRendered ]] && { echo -ne "$(<${LocalhistHelpRendered})"; echo; return; }
     LocalhistHelpRendered=$(mktemp) # This rendering is noticeably slower the first time thru, thus
                                     # the tmpfile cache...
-    egrep '^#   l' ~/bin/localhist | cut -c 3- | help_highlight | tee ${LocalhistHelpRendered}
+    egrep '^#   l' ${LocalhistHome}/localhist | cut -c 3- | help_highlight | tee ${LocalhistHelpRendered}
 }
 
 localhist() {
     [[ -z $1 ]] && { localhist help; echo -en "  \033[;33mNow:" $'\U27a9' " " ; localhist show; echo -en "\033[;0m"; return; }
     while [[ -n $1 ]]; do
         case $1 in
+            -v|--version)
+                ${LocalhistHome}/localhist-version.sh
+            ;;
             o|on)
                 if [[ $HISTFILE == $PWD/bash_history ]] ; then
                     echo Already on
@@ -183,11 +185,11 @@ localhist() {
             ;;
             z|merge)
                 shift
-                localhist-merge.sh "$@" -o $HISTFILE
+                ${LocalhistHome}/localhist-merge.sh "$@" -o $HISTFILE
                 set --
             ;;
             l|clean)
-                histfile-cleanup.sh $HISTFILE || return;
+                ${LocalhistHome}/localhist-cleanup.sh $HISTFILE || return;
                 echo "Ok: cleaned $HISTFILE"
             ;;
             mem|memclean)
@@ -232,12 +234,12 @@ localhist() {
             ;;
             g|grep)
                 shift
-                localhist-grep.sh "$@"
+                ${LocalhistHome}/localhist-grep.sh "$@"
                 set --
             ;;
             t|catalog)
                 shift
-                localhist-catalog.sh
+                ${LocalhistHome}/localhist-catalog.sh
             ;;
             h|help)
                 localhist_help
@@ -251,3 +253,9 @@ localhist() {
         shift
     done
 }
+
+[[ -z $LocalhistHome ]] && { 
+    export LocalhistHome=$(localhist-version.sh | cut -f1)
+    LocalhistHome=${LocalhistHome%%/localhist}
+}
+
